# Generated by Django 5.1.1 on 2024-09-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('brend', models.CharField(max_length=100)),
                ('narx', models.IntegerField()),
                ('rang', models.CharField(max_length=100)),
            ],
        ),
    ]
