# Generated by Django 5.0.6 on 2024-09-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastur', '0004_janr_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
